name: gevero
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  http: ^0.13.4
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/plow.jpg
    - assets/irrigation.jpg
    - assets/fertilizer.jpg
    - assets/tractor.jpg
    - assets/harvester.jpg
    - assets/seeder.jpg
